version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: on-failure
    volumes:
      - .:/flight_mate
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.9-alpine
    restart: always
    ports:
      - "5672:5672"
    depends_on:
      - app

  rabbit-worker:
    build: .
    restart: on-failure
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    env_file:
      - .env
    command: celery -A flight_mate worker -B -l info
    depends_on:
      - rabbitmq

#  nginx:
#    build: nginx
#    restart: on-failure
#    depends_on:
#      - app
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./cert:/cert
#      - ./nginx:/etc/nginx/conf.d
#        - ./film_library/

volumes:
  db-data:
