# Generated by Django 4.0 on 2022-01-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('registration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('ICAO', models.CharField(max_length=3, null=True)),
                ('IATA', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_update', models.DateTimeField()),
                ('schedule_date_time', models.DateTimeField()),
                ('actual_landing_time', models.DateTimeField(null=True)),
                ('actual_off_time', models.DateTimeField(null=True)),
                ('expected_boarding_time', models.DateTimeField(null=True)),
                ('estimate_landing_time', models.DateTimeField(null=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.status')),
            ],
        ),
        migrations.CreateModel(
            name='FlightAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to_marker', models.CharField(choices=[('DEP', 'Departure airport'), ('ARR', 'Arrive airport'), ('TRAN', 'Transition airport')], max_length=4)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='airport',
            field=models.ManyToManyField(through='flight_app.FlightAirport', to='flight_app.Airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.ManyToManyField(through='flight_app.FlightStatus', to='flight_app.Status'),
        ),
    ]
