# Generated by Django 4.0.1 on 2022-01-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('registration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('ICAO', models.CharField(max_length=3, null=True)),
                ('IATA', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('last_update', models.DateTimeField()),
                ('schedule_date_time', models.DateTimeField()),
                ('actual_landing_time', models.DateTimeField(null=True)),
                ('actual_off_time', models.DateTimeField(null=True)),
                ('expected_boarding_time', models.DateTimeField(null=True)),
                ('estimate_landing_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to_marker', models.CharField(choices=[('DEP', 'Departure airport'), ('ARR', 'Arrive airport'), ('TRAN', 'Transition airport')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('wind_cdir_full', models.CharField(max_length=20, verbose_name='wind direction')),
                ('wind_spd', models.FloatField(verbose_name='wind speed')),
                ('temp', models.FloatField(verbose_name='temperature')),
                ('precip', models.IntegerField(verbose_name='precipitation, mm')),
                ('snow', models.IntegerField()),
                ('rh', models.IntegerField(verbose_name='relative humidity, %')),
                ('clouds', models.IntegerField(verbose_name='cloud coverage, %')),
            ],
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['datetime'], name='flight_app__datetim_001d24_idx'),
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight'),
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.status'),
        ),
        migrations.AddField(
            model_name='flightairport',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airport'),
        ),
        migrations.AddField(
            model_name='flightairport',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.aircraft'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airline'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airport',
            field=models.ManyToManyField(through='flight_app.FlightAirport', to='flight_app.Airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='status',
            field=models.ManyToManyField(through='flight_app.FlightStatus', to='flight_app.Status'),
        ),
    ]
