# Generated by Django 4.0 on 2021-12-09 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.CharField(max_length=10)),
                ('aircraft_registration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.IntegerField()),
                ('airline_ICAO', models.CharField(max_length=3)),
                ('airline_IATA', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(max_length=15)),
                ('schedule_date_time', models.DateTimeField()),
                ('actual_landing_time', models.DateTimeField()),
                ('actual_off_time', models.DateTimeField()),
                ('expected_boarding_time', models.DateTimeField()),
                ('estimate_landing_time', models.DateTimeField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airline')),
            ],
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=3)),
                ('flight_status', models.ManyToManyField(through='flight_app.FlightStatus', to='flight_app.Flight')),
            ],
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.status'),
        ),
        migrations.CreateModel(
            name='FlightAirport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to_marker', models.CharField(choices=[('DEP', 'Departure airport'), ('ARR', 'Arrive airport'), ('TRAN', 'Transition airport')], max_length=4)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='flight_airport',
            field=models.ManyToManyField(through='flight_app.FlightAirport', to='flight_app.Flight'),
        ),
    ]
