# Generated by Django 4.0 on 2021-12-24 14:44
"""Create all statuses for Status Model"""
from django.db import migrations

# ALL flight statuses
STATUSES = ('SCH', 'AIR', 'EXP', 'FIR', 'LND', 'FIB', 'ARR', 'DIV', 'CNX',
            'TOM', 'DEL', 'WIL', 'GTO', 'BRD', 'GCL', 'GTD', 'DEP', 'GCH')


def insert_statuses(apps, schema_editor):
    """Insert statuses into Status model"""
    Status = apps.get_model('flight_app', 'Status')

    for value in STATUSES:
        Status.objects.create(name=value)


class Migration(migrations.Migration):
    dependencies = [
        ('flight_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_statuses),
    ]
