# Generated by Django 4.0 on 2021-12-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_rename_aircraft_registration_aircraft_registration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='airport_flight',
            new_name='airport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='status_flight',
            new_name='status',
        ),
    ]
