# Generated by Django 4.0 on 2022-01-10 10:03
"""Create base Schiphol Amsterdam airport"""
from django.db import migrations

from flight_mate.settings import AMSTERDAM_BASE_AIRPORT_NAME


def insert_airport(apps, schema_editor):
    Airport = apps.get_model('flight_app', 'Airport')
    Airport.objects.create(name=AMSTERDAM_BASE_AIRPORT_NAME)


class Migration(migrations.Migration):
    dependencies = [
        ('flight_app', '0002_add_data_into_Status_model'),
    ]

    operations = [
        migrations.RunPython(insert_airport),
    ]
