# Generated by Django 4.0.1 on 2022-02-01 11:17
"""Create ElasticSearch index mapping
    all code in flight_app.management.commands.es_index_mapping file
    it's the custom command"""

from django.db import migrations

from flight_app.management.commands.es_index_mapping import Command


def create_ES_mapping(apps, schema_editor):
    """create instance of Command (flight_app.management.commands.es_index_mapping)
     and call handle method"""
    create_mapping = Command()
    create_mapping.handle()


class Migration(migrations.Migration):
    dependencies = [
        ('flight_app', '0003_add_airport_Schiphol'),
    ]

    operations = [
        migrations.RunPython(create_ES_mapping),
    ]
