# Generated by Django 4.0.1 on 2022-02-01 11:17
"""Create ElasticSearch index mapping
    all code in service_es_mapping.py file"""

from django.db import migrations

from flight_app.service_es_mapping import create_es_mapping


def es_mapping(apps, schema_editor):
    """Create django custom command, for create ElasticSearch index with mapping
        Name - ELASTIC_INDEX_NAME, hosts - ELASTIC_HOST(look settings.py)
        and body - index_mapping(for code look create_es_mapping.py)"""
    create_es_mapping()


class Migration(migrations.Migration):
    dependencies = [
        ('flight_app', '0003_add_airport_Schiphol'),
    ]

    operations = [
        migrations.RunPython(es_mapping),
    ]
