# Generated by Django 4.0.1 on 2022-01-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0003_add_airport_Schiphol'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aircraft',
            index=models.Index(fields=['registration', 'type'], name='flight_app__registr_6dec97_idx'),
        ),
        migrations.AddIndex(
            model_name='airline',
            index=models.Index(fields=['code', 'ICAO', 'IATA'], name='flight_app__code_35d5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='airport',
            index=models.Index(fields=['name'], name='flight_app__name_889fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['schedule_date_time'], name='flight_app__schedul_1848b9_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['name'], name='flight_app__name_706b34_idx'),
        ),
    ]
