# Generated by Django 4.0.2 on 2022-02-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0005_airport_city_airport_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='public_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
