# Generated by Django 4.0.2 on 2022-02-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0006_airport_public_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='city',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='public_name',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
